### ISSUE TITLE
Documentation Confusion

### ISSUE THREAD

**Issue by zachwaggoner** [jpf/okta-social-auth-demo-app#1]
I was following the documentation and it took me a second to remember that I would have to restart the server after I set the API Token and hit submit.  Maybe its just me but after a user hits submit it might be useful to remind them to restart the server in order for the changes to take place.

Follow the instructions on the Admin page. After configuring the "Base URL" and "API Token", click on the green "Submit" button
Click the blue "Home" button
**Restart Server**
Head back to localhost:3000
You should now see a purple "Log in with Facebook" button, click that button.

Thanks :)

**Comment by jpf** [comment]
Thanks for the issue! Sorry that this took so long for me to see :disappointed:
